In [1]:
import sys
from z3 import *
import numpy as np
from complex import Complex, I
from ComplexVector import ComplexVector
from QuantumChecker import QuantumChecker
import QuantumOps as qo
import cmath, re

[And(x.r*x.r - x.i*x.i == -2, 0 == x.r*x.i + x.i*x.r)]
sat
x = (-1.4142135623?)*I
-2
[And(x.r*x.r - x.i*x.i == -2, 0 == x.r*x.i + x.i*x.r),
 x.i != -1]
sat
[x.i = -1.4142135623?, x.r = 0]
sat
((1*(3 + 0) - 0*(0 + 1))*(3 + 0) -
 (1*(0 + 1) + 0*(3 + 0))*(0 + 1))*
((5 - 0)/((5 - 0)*(5 - 0) + (0 - 1)*(0 - 1))) -
((1*(3 + 0) - 0*(0 + 1))*(0 + 1) +
 (1*(0 + 1) + 0*(3 + 0))*(3 + 0))*
(-(0 - 1)/((5 - 0)*(5 - 0) + (0 - 1)*(0 - 1))) + (((1*(3 + 0) - 0*(0 + 1))*(3 + 0) -
 (1*(0 + 1) + 0*(3 + 0))*(0 + 1))*
(-(0 - 1)/((5 - 0)*(5 - 0) + (0 - 1)*(0 - 1))) +
((1*(3 + 0) - 0*(0 + 1))*(0 + 1) +
 (1*(0 + 1) + 0*(3 + 0))*(3 + 0))*
((5 - 0)/((5 - 0)*(5 - 0) + (0 - 1)*(0 - 1))))*I
((((1*(3 + 0) - 0*(0 + 1))*(3 + 0) -
   (1*(0 + 1) + 0*(3 + 0))*(0 + 1))*
  (3 + 0) -
  ((1*(3 + 0) - 0*(0 + 1))*(0 + 1) +
   (1*(0 + 1) + 0*(3 + 0))*(3 + 0))*
  (0 + 1))/
 ((((1*(3 + 0) - 0*(0 + 1))*(3 + 0) -
    (1*(0 + 1) + 0*(3 + 0))*(0 + 1))*
   (3 + 0) -
   ((1*(3 + 0) - 0*(0 + 1))*(0 + 1) +
    (1*(0 + 1) + 0*(3 + 0))*(3 + 

In [2]:
qc = QuantumChecker()
qc.init_new_qreg('x', 2)
qc.init_new_qreg('y', 1)
qc.apply_sing_op(qo.X, 'y', 0)
qc.apply_H('y', 0)
qc.apply_ctrl(qo.rotX(np.pi/3), 'y', 0, 'x', 1)
qc.print_solver()

[[1.       +0.j  0.       +0.j  0.       +0.j  0.       +0.j
  0.       +0.j  0.       +0.j  0.       +0.j  0.       +0.j ]
 [0.       +0.j  1.       +0.j  0.       +0.j  0.       +0.j
  0.       +0.j  0.       +0.j  0.       +0.j  0.       +0.j ]
 [0.       +0.j  0.       +0.j  1.       +0.j  0.       +0.j
  0.       +0.j  0.       +0.j  0.       +0.j  0.       +0.j ]
 [0.       +0.j  0.       +0.j  0.       +0.j  1.       +0.j
  0.       +0.j  0.       +0.j  0.       +0.j  0.       +0.j ]
 [0.       +0.j  0.       +0.j  0.       +0.j  0.       +0.j
  0.8660254+0.j  0.       +0.j  0.       +0.5j 0.       +0.j ]
 [0.       +0.j  0.       +0.j  0.       +0.j  0.       +0.j
  0.       +0.j  0.8660254+0.j  0.       +0.j  0.       +0.5j]
 [0.       +0.j  0.       +0.j  0.       +0.j  0.       +0.j
  0.       -0.5j 0.       +0.j  0.8660254+0.j  0.       +0.j ]
 [0.       +0.j  0.       +0.j  0.       +0.j  0.       +0.j
  0.       +0.j  0.       -0.5j 0.       +0.j  0.8660254+0.j ]]
[And(t0

In [3]:
qc.print_model()

[t0_q__0.r = 1,
 t0_q__0.i = 0,
 sqrt2 = 1.4142135623?,
 t3_q__7.i = 0,
 t3_q__7.r = 0,
 t3_q__6.i = 0.3535533905?,
 t3_q__6.r = 0,
 t3_q__5.i = 0,
 t3_q__5.r = 0,
 t3_q__4.i = 0,
 t3_q__4.r = -0.6123724356?,
 t3_q__3.i = 0,
 t3_q__3.r = 0,
 t3_q__2.i = 0,
 t3_q__2.r = 0,
 t3_q__1.i = 0,
 t3_q__1.r = 0,
 t3_q__0.i = 0,
 t3_q__0.r = 0.7071067811?,
 t2_q__7.i = 0,
 t2_q__7.r = 0,
 t2_q__6.i = 0,
 t2_q__6.r = 0,
 t2_q__5.i = 0,
 t2_q__5.r = 0,
 t2_q__4.i = 0,
 t2_q__4.r = -0.7071067811?,
 t2_q__3.i = 0,
 t2_q__3.r = 0,
 t2_q__2.i = 0,
 t2_q__2.r = 0,
 t2_q__1.i = 0,
 t2_q__1.r = 0,
 t2_q__0.i = 0,
 t2_q__0.r = 0.7071067811?,
 t1_q__7.i = 0,
 t1_q__7.r = 0,
 t1_q__6.i = 0,
 t1_q__6.r = 0,
 t1_q__5.i = 0,
 t1_q__5.r = 0,
 t1_q__4.i = 0,
 t1_q__4.r = 1,
 t1_q__3.i = 0,
 t1_q__3.r = 0,
 t1_q__2.i = 0,
 t1_q__2.r = 0,
 t1_q__1.i = 0,
 t1_q__1.r = 0,
 t1_q__0.i = 0,
 t1_q__0.r = 0,
 t0_q__7.i = 0,
 t0_q__7.r = 0,
 t0_q__6.i = 0,
 t0_q__6.r = 0,
 t0_q__5.i = 0,
 t0_q__5.r = 0,
 t0_q__4.i = 0,
 t

In [4]:
exH = 1/np.sqrt(2) * np.array([[1,1],[1,-1]])
exOp = np.identity(8)
ctrl = 2
tgt = 1
op_size = 8
N = 2**ctrl
M = 2**tgt

for row in range(0, op_size):
    if (row & (1 << ctrl)):
        if (row & (1<<tgt)):
            exOp[row][row - M] = exH[1][0]
            exOp[row][row] = exH[1][1]
        else:
            exOp[row][row] = exH[0][0]
            exOp[row][row + M] = exH[0][1]
        print(row)
    print(exOp[row])

[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
4
[0.         0.         0.         0.         0.70710678 0.
 0.70710678 0.        ]
5
[0.         0.         0.         0.         0.         0.70710678
 0.         0.70710678]
6
[ 0.          0.          0.          0.          0.70710678  0.
 -0.70710678  0.        ]
7
[ 0.          0.          0.          0.          0.          0.70710678
  0.         -0.70710678]
